### ISSUE TITLE
calphy does not use NVT ensemble

### ISSUE THREAD

**Issue by ZAhra-Rjz** [srmnitc/calphy-publication-examples#2] opened 2024-04-18 11:41 UTC
I want to calculate free energy for a range of temperatures: **300 -2400**, with NVT. 
According to Calphy documentation, if I use **mode: ts and npt: True**, then it does the NPT calculation. otherwise, the NVT ensemble is used. it means if I use **mode: ts and npt: False**, then NVT ensemble is used.
I tried many times with these changes but in both ways when I check calphy.log it shows npt ensemble is used.

Am i doing something wrong?

**Comment by srmnitc** [comment] 2024-04-24 11:41
Could you please post your calphy.log file, and your input file?

**Comment by ZAhra-Rjz** [comment] 2024-04-26 14:51
I uploded input scripts of npt and nvt calculation. also calphy.log files. I usually check log.lammps file that shows me for both cases npt is considered. So, I uploaded log file also for you.

Thank you

[nvt-log.lammps.txt](https://github.com/srmnitc/calphy-publication-examples/files/15132049/nvt-log.lammps.txt)
[npt-calphy.log](https://github.com/srmnitc/calphy-publication-examples/files/15132051/npt-calphy.log)
[npt-log.lammps.txt](https://github.com/srmnitc/calphy-publication-examples/files/15132052/npt-log.lammps.txt)
[nvt-calphy.log](https://github.com/srmnitc/calphy-publication-examples/files/15132053/nvt-calphy.log)
[npt.yaml.txt](https://github.com/srmnitc/calphy-publication-examples/files/15132063/npt.yaml.txt)
[nvt.yaml.txt](https://github.com/srmnitc/calphy-publication-examples/files/15132064/nvt.yaml.txt)

**Comment by srmnitc** [comment] 2024-04-29 11:20
Thanks! It looks like a bug. I will transfer this issue to calphy repo, and fix it. Thanks for reporting.

**Comment by ZAhra-Rjz** [comment] 2024-04-30 10:46
Ok. Thank you. 
How long does it take to fix the bug? Can you inform me whenever it is fixed?

**Comment by srmnitc** [comment] 2024-04-30 12:04
Hi @ZAhra-Rjz I will comment and tag you when its done. I think this could be fixed this week, around Thursday should be ok.

**Comment by srmnitc** [comment] 2024-05-20 21:20
Hi @ZAhra-Rjz I was unable to reproduce this error. Upon taking a closer look, it seems that use have used the `npt` keyword under `md` section. This is not correct. `npt` is one of the main keywords, appearing under `calculations`, see [docs](https://calphy.org/en/latest/inputfile.html#calculations). I am going to go ahead and close this issue, feel free to reopen if needed.

**Closed as completed by srmnitc** 2024-05-20 21:20 UTC
Labels: bug
